### ISSUE TITLE
Adjust the values to be whole numbers (ie smaller space needed in the column for values (ie where the cm is displayed)

### ISSUE THREAD

**Issue by BeauTurner** [hanskellner/Fusion360Voronoi#1]
Any reason not to adjust the float values to integer whole numbers only for the values of # Cells, Area Width, Area Height, % Scale Cell that contains the required cm designation? Ie really looking to take that data and make it easier to read as a whole number. Where is the width controlled at (visually) for these values?

**Comment by hanskellner** [comment]
Thx for the prompting ;) Done!

**Comment by BeauTurner** [comment]
Excellent, have not checked yet to confirm but does this fix all four fields as having the same "width" visually in the dialog box? Where is that portion controlled at (could not find it in the js file).

**Comment by hanskellner** [comment]
The layout of the controls is automatic. With the changes I made the layout it much improved. Not sure why the other controls are so poorly aligned. You can see a snapshot of the new layout on the main page of the project (readme).
