### ISSUE TITLE
Fusion 360 No longer supports java script.

### ISSUE THREAD

**Issue by SirDragonClaw** [hanskellner/Fusion360Voronoi#4]
Scripts are only supported in c++ and python as far as I can tell.

**Comment by hanskellner** [comment]
Hi Dan - You can still run a JavaScript addin, just not create a new script through the application.  See this post:

https://forums.autodesk.com/t5/fusion-360-api-and-scripts/image-2-surface-script-for-fusion-360/m-p/7324273#M4403

Therefore, this script can still be loaded in Fusion 360.  I do have plans to create a newer version that will be implemented in Python or C++.
