### ISSUE TITLE
.manifest file missing?

### ISSUE THREAD

**Issue by Duros** [hanskellner/Fusion360Voronoi#5]
Hello Hans,

I am trying to get your plugin to work. but I am receiving the following error when trying to add the script to "**My Scripts**" when I press the **+** button
![fusion 360 add-in](https://user-images.githubusercontent.com/10384150/36431352-a88dfbda-1657-11e8-80b9-b77ad17daa07.png)

I have been looking around the web to get this to work, and came across a topic that said that there should be a .manifest file added to the folder to get it to work? Any ideas if this is correct?

Thanks,
Duros

**Comment by Jonnie-Cache** [comment]
I have the same problem. @Duros did you ever figure it out?

**Comment by Duros** [comment]
@Jonnie-Cache, unfortunately not. I tried adding a .manifest file from another plug-in @hanskellner made. But didn't get it to work.

**Comment by hanskellner** [comment]
The above error occurs when a script or addin is placed in the same folder as another script or addin.  Please unarchive the files into an empty new folder.  Also, a manifest file is now included in the repo.
